import { ProjectInfo } from './analyzer';
import { generateWithAI } from './ai';
import * as fs from 'fs';

export type GeneratorMode = 'readme' | 'api' | 'full';

export async function generateDocs(
  info: ProjectInfo,
  mode: GeneratorMode = 'readme',
  useAI = true
): Promise<{ readme: string; api?: string }> {
  
  if (useAI) {
    return generateWithAIAssist(info, mode);
  }
  
  return generateBasic(info, mode);
}

async function generateWithAIAssist(
  info: ProjectInfo,
  mode: GeneratorMode
): Promise<{ readme: string; api?: string }> {
  
  // Read a sample of source files for context
  const sourceContext = info.sourceFiles.slice(0, 5).map(file => {
    try {
      const content = fs.readFileSync(file, 'utf-8');
      return `--- ${file} ---\n${content.slice(0, 1000)}`;
    } catch {
      return '';
    }
  }).join('\n\n');

  const prompt = `Generate a professional README.md for this project:

Project Name: ${info.name}
Description: ${info.description || 'No description provided'}
Version: ${info.version}
Language: ${info.language}
Dependencies: ${info.dependencies.slice(0, 10).join(', ')}
Scripts: ${Object.entries(info.scripts).map(([k, v]) => `${k}: ${v}`).join(', ')}
License: ${info.license || 'Not specified'}

Source code samples:
${sourceContext}

${info.existingReadme ? `Existing README (improve upon this):\n${info.existingReadme.slice(0, 500)}` : ''}

Generate a complete README with:
1. Project title and description
2. Features (infer from code if needed)
3. Installation instructions
4. Usage examples (based on the code)
5. Configuration (if applicable)
6. Contributing section
7. License

Use badges where appropriate. Be concise but informative.`;

  const readme = await generateWithAI(prompt);
  
  const result: { readme: string; api?: string } = { readme };
  
  if (mode === 'api' || mode === 'full') {
    result.api = await generateAPIDoc(info);
  }
  
  return result;
}

async function generateAPIDoc(info: ProjectInfo): Promise<string> {
  const prompt = `Based on this ${info.language} project, generate API documentation:

Project: ${info.name}
Files: ${info.sourceFiles.join(', ')}

Generate:
1. Overview
2. Endpoints/Functions (infer from common patterns)
3. Request/Response examples
4. Error codes

If this doesn't appear to be an API project, generate function/module documentation instead.`;

  return generateWithAI(prompt);
}

function generateBasic(info: ProjectInfo, mode: GeneratorMode): { readme: string; api?: string } {
  // Fallback: Generate without AI
  const readme = `# ${info.name}

${info.description || 'A ' + info.language + ' project.'}

## Installation

\`\`\`bash
${getInstallCommand(info)}
\`\`\`

## Usage

\`\`\`bash
${getUsageCommand(info)}
\`\`\`

## Scripts

${Object.entries(info.scripts).map(([name, cmd]) => `- \`npm run ${name}\`: ${cmd}`).join('\n')}

## Dependencies

${info.dependencies.map(dep => `- ${dep}`).join('\n')}

## License

${info.license || 'See LICENSE file'}

---
*Generated by [DocBot](https://synthwork.io)*
`;

  return { readme };
}

function getInstallCommand(info: ProjectInfo): string {
  switch (info.language) {
    case 'javascript':
    case 'typescript':
      return 'npm install';
    case 'python':
      return 'pip install -e .';
    case 'rust':
      return 'cargo build';
    case 'go':
      return 'go build';
    default:
      return '# See installation instructions';
  }
}

function getUsageCommand(info: ProjectInfo): string {
  if (info.scripts.start) return 'npm start';
  if (info.scripts.dev) return 'npm run dev';
  if (info.mainFile) return `node ${info.mainFile}`;
  return '# See usage instructions';
}
